import User from "../models/UserModel.js";
import bcrypt from "bcrypt";
import { generateToken } from '../middleware/generateToken.js'

export const googleSignIn = async(req, res) => {
    const { username, email, photo } = req.body

    const user = await User.findOne({ email })

    if(user){
        res.status(200).json({
            _id: user._id,
            username: user.username,
            email: user.email,
            image: user.image,
            subscribers: user.subscribers,
            subscribedUsers: user.subscribedUsers,
            token: generateToken(user._id),
            createdAt: user.createdAt,
            favorites: user.favorites,
            admin: user.admin,
            verified: user.verified,
            superUser: user.superUser
        })
    }else {
        const generatedPassword = Math.random().toString(36).slice(-8)
        const hashedPassword = await bcrypt.hash(generatedPassword, 10)

        function getRandomInt(max){
            return Math.floor(Math.random() * max)
        }

        let newUsername = adjectives[getRandomInt(adjectives.length)] + nouns[getRandomInt(nouns.length)];
        

        const newUser = await User.create({
            username: newUsername,
            email,
            password: hashedPassword,
            image: photo
        
        })

        if(newUser){
            res.status(201).json({
                _id: newUser._id,
                username: newUser.username,
                email: newUser.email,
                image: newUser.image,
                subscribers: newUser.subscribers,
                subscribedUsers: newUser.subscribedUsers,
                token: generateToken(newUser._id),
                createdAt: newUser.createdAt,
                favorites: newUser.favorites,
                admin: newUser.admin,
                verified: newUser.verified,
                superUser: newUser.superUser
            })
        }
    }

}



const adjectives = [
    "Adorable",
    "Beautiful",
    "Charming",
    "Delightful",
    "Elegant",
    "Fancy",
    "Gorgeous",
    "Handsome",
    "Innocent",
    "Joyful",
    "Kind",
    "Lovely",
    "Magnificent",
    "Neat",
    "Outstanding",
    "Pretty",
    "Quaint",
    "Radiant",
    "Shiny",
    "Tender",
    "Unique",
    "Vibrant",
    "Wonderful",
    "Youthful",
    "Zealous",
    "Amazing",
    "Brilliant",
    "Cheerful",
    "Dazzling",
    "Exquisite",
    "Fascinating",
    "Glorious",
    "Happy",
    "Intelligent",
    "Jovial",
    "Lively",
    "Marvelous",
    "Nice",
    "Optimistic",
    "Playful",
    "Quiet",
    "Resplendent",
    "Splendid",
    "Tremendous",
    "Vivid",
    "Witty",
    "Zeal",
    "Blissful",
    "Captivating",
    "Divine",
    "Excellent",
    "Fantastic",
    "Graceful",
    "Harmonious",
    "Inspiring",
    "Jubilant",
    "Luxurious",
    "Majestic",
    "Noble",
    "Opulent",
    "Precious",
    "Ravishing",
    "Serene",
    "Thrilling",
    "Valiant",
    "Whimsical",
    "Zen",
    "Adventurous",
    "Bold",
    "Charismatic",
    "Dynamic",
    "Energetic",
    "Fearless",
    "Gregarious",
    "Heroic",
    "Inventive",
    "Jazzy",
    "Kinetic",
    "Luminous",
    "Magnetic",
    "Optimistic",
    "Passionate",
    "Resilient",
    "Sensational",
    "Tangible",
    "Vibrant",
    "Wondrous",
    "Zealous",
    "Alluring",
    "Bewitching",
    "Confident",
    "Daring",
    "Eloquent",
    "Fierce",
    "Graceful",
    "Hypnotic",
    "Intriguing",
    "Jubilant",
    "Keen",
    "Luscious",
    "Mysterious",
    "Opulent",
    "Playful",
    "Radiant",
    "Seductive",
    "Tantalizing",
    "Vivacious",
    "Whimsical",
];

const nouns = [
    "Apple",
    "Banana",
    "Car",
    "Dog",
    "Elephant",
    "Flower",
    "Guitar",
    "House",
    "Ice Cream",
    "Jacket",
    "Kite",
    "Lion",
    "Mountain",
    "Notebook",
    "Ocean",
    "Piano",
    "Quilt",
    "River",
    "Sun",
    "Tree",
    "Umbrella",
    "Violin",
    "Waterfall",
    "Xylophone",
    "Yacht",
    "Zebra",
    "Airplane",
    "Beach",
    "Cat",
    "Desk",
    "Earth",
    "Forest",
    "Globe",
    "Hat",
    "Island",
    "Jungle",
    "Key",
    "Laptop",
    "Moon",
    "Nest",
    "Orchard",
    "Penguin",
    "Queen",
    "Rainbow",
    "Star",
    "Teapot",
    "Unicorn",
    "Volcano",
    "Wallet",
    "Xylophonist",
    "Yard",
    "Zeppelin",
    "Arch",
    "Butterfly",
    "Castle",
    "Dolphin",
    "Eagle",
    "Fountain",
    "Garden",
    "Hammer",
    "Igloo",
    "Jar",
    "Kangaroo",
    "Lemon",
    "Map",
    "Ninja",
    "Octopus",
    "Puzzle",
    "Quilt",
    "Rocket",
    "Ship",
    "Turtle",
    "Unicorn",
    "Vase",
    "Whale",
    "Xylophone",
    "Yogurt",
    "Zebra",
    "Anchor",
    "Book",
    "Candle",
    "Dragon",
    "Egg",
    "Fire",
    "Guitar",
    "Hammer",
    "Ice",
    "Jewel",
    "Kite",
    "Lamp",
    "Magnet",
    "Nail",
    "Owl",
    "Pencil",
    "Quilt",
    "Rain",
    "Snow",
    "Tiger",
    "Umbrella",
    "Vase",
    "Wind",
    "Xylophone",
    "Yarn",
    "Zeppelin",
];